---

- name: Add group
  group: name={{ build_group }} state=present
  become: true

- name: Add build user
  user: name={{ build_user }} group={{ build_group }} home=/home/{{ build_user }}
  become: true