---

- name: Install python and deps for ansible modules
  raw: dnf install -y python2 python2-dnf libselinux-python
  tags:
    - necessary_packages

- name: Installs necessary packages for fedora
  package: name={{ item }} state=latest
  with_items:
    - git
    - gcc
    - file
    - libevent-devel
    - python-devel
    - sqlite-devel
    - zeromq-devel
    - libffi-devel
    - openssl-devel
    - systemd-python
    - redis
    - couchdb
    - python2-systemd
    - make
    - python
    - python-pip
    - redhat-rpm-config
    - yum
    - nginx
  tags:
    - necessary_packages

- name: Upgrade global pip
  raw: pip install --upgrade pip

- name: Install global pip
  pip: name={{ item }}
  with_items:
    - virtualenv
    - setuptools

- name: Create dir for code
  file: path={{ path_to_code }} state=directory mode=0755 recurse=yes

- name: Clone repository
  git: repo={{ code_repository }} dest={{ path_to_code }} version={{ code_version }} update=no
  tags: clone

- name: Copy buildout
  template: src=buildout.cfg.j2 dest={{ path_to_code }}/buildout.cfg
  register: copy_buildout_config

- name: Copy auth.ini
  template: src=auth.ini.j2 dest={{ path_to_code }}/auth.ini
  register: copy_buildout_config

- name: Load buildout
  shell: "python bootstrap.py chdir={{ path_to_code }}"

- name: Build repo
  shell: "python bin/buildout -N chdir={{ path_to_code }}"

- name: Try reload webapp
  shell: "{{ path_to_code }}/bin/circusctl reload webapp"
  tags: reload_circus
  ignore_errors: yes
  register: reload_circus

- name: Run circus ini
  shell: "{{ path_to_code }}/bin/circusd --daemon"
  tags: run_circus
  when: reload_circus|failed

